[package]
name = "day-04"
version = "0.1.0"
edition = "2021"

[dependencies]
glam.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
divan.workspace = true
test-log.workspace = true
miette.workspace = true

[[bench]]
name = "day-04-bench"
path = "benches/benchmarks.rs"
harness = false